/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface CreateCoin {
    }
    interface MyntAsset {
    }
    interface MyntAssetPage {
    }
    interface MyntAssets {
    }
    interface MyntChat {
    }
    interface MyntDm {
        "name": string;
        "profImg": string;
    }
    interface MyntDms {
    }
    interface MyntFeed {
    }
    interface MyntListing {
    }
    interface MyntLogin {
    }
    interface MyntLogo {
    }
    interface MyntMakePost {
    }
    interface MyntMarket {
    }
    interface MyntMenu {
    }
    interface MyntMessage {
    }
    interface MyntNotifications {
    }
    interface MyntPage {
    }
    interface MyntPageMenu {
    }
    interface MyntPost {
        "mediaPicSrc": string;
        "name": string;
        "profPicSrc": string;
        "text": string;
        "user": string;
    }
    interface MyntProfileHeader {
    }
    interface MyntRoot {
    }
    interface MyntSettings {
    }
    interface MyntSideList {
        "ttle": string;
    }
    interface MyntSideListing {
        "image": string;
        "text": string;
    }
    interface MyntSignup {
    }
    interface MyntStories {
    }
    interface MyntStory {
    }
    interface MyntTradeModule {
    }
    interface MyntWallet {
    }
    interface MyntWatch {
    }
    interface MyntWatchRow {
        "numCols": number;
    }
    interface MyntWatchThumb {
    }
    interface ProfilePic {
        "source": string;
    }
    interface WalletCoin {
        "coinImg": string;
        "coinTitle": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCreateCoinElement extends Components.CreateCoin, HTMLStencilElement {
    }
    var HTMLCreateCoinElement: {
        prototype: HTMLCreateCoinElement;
        new (): HTMLCreateCoinElement;
    };
    interface HTMLMyntAssetElement extends Components.MyntAsset, HTMLStencilElement {
    }
    var HTMLMyntAssetElement: {
        prototype: HTMLMyntAssetElement;
        new (): HTMLMyntAssetElement;
    };
    interface HTMLMyntAssetPageElement extends Components.MyntAssetPage, HTMLStencilElement {
    }
    var HTMLMyntAssetPageElement: {
        prototype: HTMLMyntAssetPageElement;
        new (): HTMLMyntAssetPageElement;
    };
    interface HTMLMyntAssetsElement extends Components.MyntAssets, HTMLStencilElement {
    }
    var HTMLMyntAssetsElement: {
        prototype: HTMLMyntAssetsElement;
        new (): HTMLMyntAssetsElement;
    };
    interface HTMLMyntChatElement extends Components.MyntChat, HTMLStencilElement {
    }
    var HTMLMyntChatElement: {
        prototype: HTMLMyntChatElement;
        new (): HTMLMyntChatElement;
    };
    interface HTMLMyntDmElement extends Components.MyntDm, HTMLStencilElement {
    }
    var HTMLMyntDmElement: {
        prototype: HTMLMyntDmElement;
        new (): HTMLMyntDmElement;
    };
    interface HTMLMyntDmsElement extends Components.MyntDms, HTMLStencilElement {
    }
    var HTMLMyntDmsElement: {
        prototype: HTMLMyntDmsElement;
        new (): HTMLMyntDmsElement;
    };
    interface HTMLMyntFeedElement extends Components.MyntFeed, HTMLStencilElement {
    }
    var HTMLMyntFeedElement: {
        prototype: HTMLMyntFeedElement;
        new (): HTMLMyntFeedElement;
    };
    interface HTMLMyntListingElement extends Components.MyntListing, HTMLStencilElement {
    }
    var HTMLMyntListingElement: {
        prototype: HTMLMyntListingElement;
        new (): HTMLMyntListingElement;
    };
    interface HTMLMyntLoginElement extends Components.MyntLogin, HTMLStencilElement {
    }
    var HTMLMyntLoginElement: {
        prototype: HTMLMyntLoginElement;
        new (): HTMLMyntLoginElement;
    };
    interface HTMLMyntLogoElement extends Components.MyntLogo, HTMLStencilElement {
    }
    var HTMLMyntLogoElement: {
        prototype: HTMLMyntLogoElement;
        new (): HTMLMyntLogoElement;
    };
    interface HTMLMyntMakePostElement extends Components.MyntMakePost, HTMLStencilElement {
    }
    var HTMLMyntMakePostElement: {
        prototype: HTMLMyntMakePostElement;
        new (): HTMLMyntMakePostElement;
    };
    interface HTMLMyntMarketElement extends Components.MyntMarket, HTMLStencilElement {
    }
    var HTMLMyntMarketElement: {
        prototype: HTMLMyntMarketElement;
        new (): HTMLMyntMarketElement;
    };
    interface HTMLMyntMenuElement extends Components.MyntMenu, HTMLStencilElement {
    }
    var HTMLMyntMenuElement: {
        prototype: HTMLMyntMenuElement;
        new (): HTMLMyntMenuElement;
    };
    interface HTMLMyntMessageElement extends Components.MyntMessage, HTMLStencilElement {
    }
    var HTMLMyntMessageElement: {
        prototype: HTMLMyntMessageElement;
        new (): HTMLMyntMessageElement;
    };
    interface HTMLMyntNotificationsElement extends Components.MyntNotifications, HTMLStencilElement {
    }
    var HTMLMyntNotificationsElement: {
        prototype: HTMLMyntNotificationsElement;
        new (): HTMLMyntNotificationsElement;
    };
    interface HTMLMyntPageElement extends Components.MyntPage, HTMLStencilElement {
    }
    var HTMLMyntPageElement: {
        prototype: HTMLMyntPageElement;
        new (): HTMLMyntPageElement;
    };
    interface HTMLMyntPageMenuElement extends Components.MyntPageMenu, HTMLStencilElement {
    }
    var HTMLMyntPageMenuElement: {
        prototype: HTMLMyntPageMenuElement;
        new (): HTMLMyntPageMenuElement;
    };
    interface HTMLMyntPostElement extends Components.MyntPost, HTMLStencilElement {
    }
    var HTMLMyntPostElement: {
        prototype: HTMLMyntPostElement;
        new (): HTMLMyntPostElement;
    };
    interface HTMLMyntProfileHeaderElement extends Components.MyntProfileHeader, HTMLStencilElement {
    }
    var HTMLMyntProfileHeaderElement: {
        prototype: HTMLMyntProfileHeaderElement;
        new (): HTMLMyntProfileHeaderElement;
    };
    interface HTMLMyntRootElement extends Components.MyntRoot, HTMLStencilElement {
    }
    var HTMLMyntRootElement: {
        prototype: HTMLMyntRootElement;
        new (): HTMLMyntRootElement;
    };
    interface HTMLMyntSettingsElement extends Components.MyntSettings, HTMLStencilElement {
    }
    var HTMLMyntSettingsElement: {
        prototype: HTMLMyntSettingsElement;
        new (): HTMLMyntSettingsElement;
    };
    interface HTMLMyntSideListElement extends Components.MyntSideList, HTMLStencilElement {
    }
    var HTMLMyntSideListElement: {
        prototype: HTMLMyntSideListElement;
        new (): HTMLMyntSideListElement;
    };
    interface HTMLMyntSideListingElement extends Components.MyntSideListing, HTMLStencilElement {
    }
    var HTMLMyntSideListingElement: {
        prototype: HTMLMyntSideListingElement;
        new (): HTMLMyntSideListingElement;
    };
    interface HTMLMyntSignupElement extends Components.MyntSignup, HTMLStencilElement {
    }
    var HTMLMyntSignupElement: {
        prototype: HTMLMyntSignupElement;
        new (): HTMLMyntSignupElement;
    };
    interface HTMLMyntStoriesElement extends Components.MyntStories, HTMLStencilElement {
    }
    var HTMLMyntStoriesElement: {
        prototype: HTMLMyntStoriesElement;
        new (): HTMLMyntStoriesElement;
    };
    interface HTMLMyntStoryElement extends Components.MyntStory, HTMLStencilElement {
    }
    var HTMLMyntStoryElement: {
        prototype: HTMLMyntStoryElement;
        new (): HTMLMyntStoryElement;
    };
    interface HTMLMyntTradeModuleElement extends Components.MyntTradeModule, HTMLStencilElement {
    }
    var HTMLMyntTradeModuleElement: {
        prototype: HTMLMyntTradeModuleElement;
        new (): HTMLMyntTradeModuleElement;
    };
    interface HTMLMyntWalletElement extends Components.MyntWallet, HTMLStencilElement {
    }
    var HTMLMyntWalletElement: {
        prototype: HTMLMyntWalletElement;
        new (): HTMLMyntWalletElement;
    };
    interface HTMLMyntWatchElement extends Components.MyntWatch, HTMLStencilElement {
    }
    var HTMLMyntWatchElement: {
        prototype: HTMLMyntWatchElement;
        new (): HTMLMyntWatchElement;
    };
    interface HTMLMyntWatchRowElement extends Components.MyntWatchRow, HTMLStencilElement {
    }
    var HTMLMyntWatchRowElement: {
        prototype: HTMLMyntWatchRowElement;
        new (): HTMLMyntWatchRowElement;
    };
    interface HTMLMyntWatchThumbElement extends Components.MyntWatchThumb, HTMLStencilElement {
    }
    var HTMLMyntWatchThumbElement: {
        prototype: HTMLMyntWatchThumbElement;
        new (): HTMLMyntWatchThumbElement;
    };
    interface HTMLProfilePicElement extends Components.ProfilePic, HTMLStencilElement {
    }
    var HTMLProfilePicElement: {
        prototype: HTMLProfilePicElement;
        new (): HTMLProfilePicElement;
    };
    interface HTMLWalletCoinElement extends Components.WalletCoin, HTMLStencilElement {
    }
    var HTMLWalletCoinElement: {
        prototype: HTMLWalletCoinElement;
        new (): HTMLWalletCoinElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "create-coin": HTMLCreateCoinElement;
        "mynt-asset": HTMLMyntAssetElement;
        "mynt-asset-page": HTMLMyntAssetPageElement;
        "mynt-assets": HTMLMyntAssetsElement;
        "mynt-chat": HTMLMyntChatElement;
        "mynt-dm": HTMLMyntDmElement;
        "mynt-dms": HTMLMyntDmsElement;
        "mynt-feed": HTMLMyntFeedElement;
        "mynt-listing": HTMLMyntListingElement;
        "mynt-login": HTMLMyntLoginElement;
        "mynt-logo": HTMLMyntLogoElement;
        "mynt-make-post": HTMLMyntMakePostElement;
        "mynt-market": HTMLMyntMarketElement;
        "mynt-menu": HTMLMyntMenuElement;
        "mynt-message": HTMLMyntMessageElement;
        "mynt-notifications": HTMLMyntNotificationsElement;
        "mynt-page": HTMLMyntPageElement;
        "mynt-page-menu": HTMLMyntPageMenuElement;
        "mynt-post": HTMLMyntPostElement;
        "mynt-profile-header": HTMLMyntProfileHeaderElement;
        "mynt-root": HTMLMyntRootElement;
        "mynt-settings": HTMLMyntSettingsElement;
        "mynt-side-list": HTMLMyntSideListElement;
        "mynt-side-listing": HTMLMyntSideListingElement;
        "mynt-signup": HTMLMyntSignupElement;
        "mynt-stories": HTMLMyntStoriesElement;
        "mynt-story": HTMLMyntStoryElement;
        "mynt-trade-module": HTMLMyntTradeModuleElement;
        "mynt-wallet": HTMLMyntWalletElement;
        "mynt-watch": HTMLMyntWatchElement;
        "mynt-watch-row": HTMLMyntWatchRowElement;
        "mynt-watch-thumb": HTMLMyntWatchThumbElement;
        "profile-pic": HTMLProfilePicElement;
        "wallet-coin": HTMLWalletCoinElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface CreateCoin {
    }
    interface MyntAsset {
    }
    interface MyntAssetPage {
    }
    interface MyntAssets {
    }
    interface MyntChat {
    }
    interface MyntDm {
        "name"?: string;
        "profImg"?: string;
    }
    interface MyntDms {
    }
    interface MyntFeed {
    }
    interface MyntListing {
    }
    interface MyntLogin {
    }
    interface MyntLogo {
    }
    interface MyntMakePost {
    }
    interface MyntMarket {
    }
    interface MyntMenu {
    }
    interface MyntMessage {
    }
    interface MyntNotifications {
    }
    interface MyntPage {
    }
    interface MyntPageMenu {
    }
    interface MyntPost {
        "mediaPicSrc"?: string;
        "name"?: string;
        "profPicSrc"?: string;
        "text"?: string;
        "user"?: string;
    }
    interface MyntProfileHeader {
    }
    interface MyntRoot {
    }
    interface MyntSettings {
    }
    interface MyntSideList {
        "ttle"?: string;
    }
    interface MyntSideListing {
        "image"?: string;
        "text"?: string;
    }
    interface MyntSignup {
    }
    interface MyntStories {
    }
    interface MyntStory {
    }
    interface MyntTradeModule {
    }
    interface MyntWallet {
    }
    interface MyntWatch {
    }
    interface MyntWatchRow {
        "numCols"?: number;
    }
    interface MyntWatchThumb {
    }
    interface ProfilePic {
        "source"?: string;
    }
    interface WalletCoin {
        "coinImg"?: string;
        "coinTitle"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "create-coin": CreateCoin;
        "mynt-asset": MyntAsset;
        "mynt-asset-page": MyntAssetPage;
        "mynt-assets": MyntAssets;
        "mynt-chat": MyntChat;
        "mynt-dm": MyntDm;
        "mynt-dms": MyntDms;
        "mynt-feed": MyntFeed;
        "mynt-listing": MyntListing;
        "mynt-login": MyntLogin;
        "mynt-logo": MyntLogo;
        "mynt-make-post": MyntMakePost;
        "mynt-market": MyntMarket;
        "mynt-menu": MyntMenu;
        "mynt-message": MyntMessage;
        "mynt-notifications": MyntNotifications;
        "mynt-page": MyntPage;
        "mynt-page-menu": MyntPageMenu;
        "mynt-post": MyntPost;
        "mynt-profile-header": MyntProfileHeader;
        "mynt-root": MyntRoot;
        "mynt-settings": MyntSettings;
        "mynt-side-list": MyntSideList;
        "mynt-side-listing": MyntSideListing;
        "mynt-signup": MyntSignup;
        "mynt-stories": MyntStories;
        "mynt-story": MyntStory;
        "mynt-trade-module": MyntTradeModule;
        "mynt-wallet": MyntWallet;
        "mynt-watch": MyntWatch;
        "mynt-watch-row": MyntWatchRow;
        "mynt-watch-thumb": MyntWatchThumb;
        "profile-pic": ProfilePic;
        "wallet-coin": WalletCoin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "create-coin": LocalJSX.CreateCoin & JSXBase.HTMLAttributes<HTMLCreateCoinElement>;
            "mynt-asset": LocalJSX.MyntAsset & JSXBase.HTMLAttributes<HTMLMyntAssetElement>;
            "mynt-asset-page": LocalJSX.MyntAssetPage & JSXBase.HTMLAttributes<HTMLMyntAssetPageElement>;
            "mynt-assets": LocalJSX.MyntAssets & JSXBase.HTMLAttributes<HTMLMyntAssetsElement>;
            "mynt-chat": LocalJSX.MyntChat & JSXBase.HTMLAttributes<HTMLMyntChatElement>;
            "mynt-dm": LocalJSX.MyntDm & JSXBase.HTMLAttributes<HTMLMyntDmElement>;
            "mynt-dms": LocalJSX.MyntDms & JSXBase.HTMLAttributes<HTMLMyntDmsElement>;
            "mynt-feed": LocalJSX.MyntFeed & JSXBase.HTMLAttributes<HTMLMyntFeedElement>;
            "mynt-listing": LocalJSX.MyntListing & JSXBase.HTMLAttributes<HTMLMyntListingElement>;
            "mynt-login": LocalJSX.MyntLogin & JSXBase.HTMLAttributes<HTMLMyntLoginElement>;
            "mynt-logo": LocalJSX.MyntLogo & JSXBase.HTMLAttributes<HTMLMyntLogoElement>;
            "mynt-make-post": LocalJSX.MyntMakePost & JSXBase.HTMLAttributes<HTMLMyntMakePostElement>;
            "mynt-market": LocalJSX.MyntMarket & JSXBase.HTMLAttributes<HTMLMyntMarketElement>;
            "mynt-menu": LocalJSX.MyntMenu & JSXBase.HTMLAttributes<HTMLMyntMenuElement>;
            "mynt-message": LocalJSX.MyntMessage & JSXBase.HTMLAttributes<HTMLMyntMessageElement>;
            "mynt-notifications": LocalJSX.MyntNotifications & JSXBase.HTMLAttributes<HTMLMyntNotificationsElement>;
            "mynt-page": LocalJSX.MyntPage & JSXBase.HTMLAttributes<HTMLMyntPageElement>;
            "mynt-page-menu": LocalJSX.MyntPageMenu & JSXBase.HTMLAttributes<HTMLMyntPageMenuElement>;
            "mynt-post": LocalJSX.MyntPost & JSXBase.HTMLAttributes<HTMLMyntPostElement>;
            "mynt-profile-header": LocalJSX.MyntProfileHeader & JSXBase.HTMLAttributes<HTMLMyntProfileHeaderElement>;
            "mynt-root": LocalJSX.MyntRoot & JSXBase.HTMLAttributes<HTMLMyntRootElement>;
            "mynt-settings": LocalJSX.MyntSettings & JSXBase.HTMLAttributes<HTMLMyntSettingsElement>;
            "mynt-side-list": LocalJSX.MyntSideList & JSXBase.HTMLAttributes<HTMLMyntSideListElement>;
            "mynt-side-listing": LocalJSX.MyntSideListing & JSXBase.HTMLAttributes<HTMLMyntSideListingElement>;
            "mynt-signup": LocalJSX.MyntSignup & JSXBase.HTMLAttributes<HTMLMyntSignupElement>;
            "mynt-stories": LocalJSX.MyntStories & JSXBase.HTMLAttributes<HTMLMyntStoriesElement>;
            "mynt-story": LocalJSX.MyntStory & JSXBase.HTMLAttributes<HTMLMyntStoryElement>;
            "mynt-trade-module": LocalJSX.MyntTradeModule & JSXBase.HTMLAttributes<HTMLMyntTradeModuleElement>;
            "mynt-wallet": LocalJSX.MyntWallet & JSXBase.HTMLAttributes<HTMLMyntWalletElement>;
            "mynt-watch": LocalJSX.MyntWatch & JSXBase.HTMLAttributes<HTMLMyntWatchElement>;
            "mynt-watch-row": LocalJSX.MyntWatchRow & JSXBase.HTMLAttributes<HTMLMyntWatchRowElement>;
            "mynt-watch-thumb": LocalJSX.MyntWatchThumb & JSXBase.HTMLAttributes<HTMLMyntWatchThumbElement>;
            "profile-pic": LocalJSX.ProfilePic & JSXBase.HTMLAttributes<HTMLProfilePicElement>;
            "wallet-coin": LocalJSX.WalletCoin & JSXBase.HTMLAttributes<HTMLWalletCoinElement>;
        }
    }
}
